import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const paths={meta:'web/src/meta.ts',pkg:'package.json',release:'RELEASE_NOTES.md',gradle:'app/build.gradle.kts',native:'app/src/main/java/com/dolphin/calendar/MainActivity.kt',manifest:'app/src/main/AndroidManifest.xml',webNative:'web/src/lib/native.ts',nav:'web/src/nav/useNavigation.ts',css:'web/src/theme/app.css',storage:'web/src/lib/storage.ts',state:'web/src/state/AppState.tsx',dialog:'web/src/components/Dialog.tsx',import:'web/src/lib/import.ts',sheet:'web/src/components/CourseSheet.tsx',settings:'web/src/screens/Settings.tsx',notifications:'app/src/main/java/com/dolphin/calendar/Notifications.kt',scheduler:'app/src/main/java/com/dolphin/calendar/ReminderScheduler.kt'};
const sources=Object.fromEntries(await Promise.all(Object.entries(paths).map(async([key,file])=>[key,await readFile(file,'utf8')])));
const version=sources.meta.match(/APP_VERSION\s*=\s*'([\d.]+)'/)[1];
const rules=[
 {id:'版本唯一来源',key:'pkg',test:s=>{assert.equal(JSON.parse(s.pkg).version,version);assert.match(s.release,new RegExp(`^## ${version.replaceAll('.','\\.')}`, 'm'));assert.match(s.gradle,/versionParts\[0\] \* 10000 \+ versionParts\[1\] \* 100/);assert.match(s.gradle,/web\/src\/meta.ts/);},bad:s=>s.replace(JSON.stringify(version),'"9.9.9"')},
 {id:'IndexedDB 本地存储',key:'storage',test:s=>assert.match(s.storage,/indexedDB\.open\(DATABASE,1\)/),bad:s=>s.replace('indexedDB.open','removed.open')},
 {id:'落库后统一推送状态',key:'state',test:s=>assert.match(s.state,/await saveData\(next\);[\s\S]*latest.current=next;setData\(next\)/),bad:s=>s.replace('setData(next)','void(next)')},
 {id:'自定义对话框命令式打开',key:'dialog',test:s=>assert.match(s.dialog,/if\(open\) ref.current\?\.show\(\)/),bad:s=>s.replace('?.show()','?.focus()')},
 {id:'用户关闭先处理草稿保护',key:'dialog',test:s=>{assert.match(s.dialog,/cancel=\(event:Event\)=>\{event.preventDefault\(\);request\(\);\}/);assert.match(s.dialog,/addEventListener\('dolphin-close-request',request\)/);assert.match(s.dialog,/if\(programmatic.current\)programmatic.current=false;else request\(\)/);},bad:s=>s.replace('event.preventDefault()','void(event)')},
 {id:'同一 Web 构建同步到 APK',key:'gradle',test:s=>{assert.match(s.gradle,/dependsOn\(buildWeb\)/);assert.match(s.gradle,/dependsOn\(syncWeb\)/);assert.match(s.gradle,/rootProject.file\("web\/dist"\)/);},bad:s=>s.replace('dependsOn(buildWeb)','dependsOn()')},
 {id:'原生相机采集分流与指定输出',key:'native',test:s=>{assert.match(s.native,/params.isCaptureEnabled/);assert.match(s.native,/MediaStore.EXTRA_OUTPUT, uri/);assert.match(s.native,/captureUri\?\.let \{ arrayOf\(it\) \}/);},bad:s=>s.replace('params.isCaptureEnabled','false')},
 {id:'安全 https 资源加载与调试隔离',key:'native',test:s=>{assert.match(s.native,/WebViewAssetLoader.Builder/);assert.match(s.native,/allowFileAccess = false/);assert.match(s.native,/setWebContentsDebuggingEnabled\(BuildConfig.DEBUG\)/);assert.match(s.gradle,/applicationIdSuffix = ".debug"/);},bad:s=>s.replace('setWebContentsDebuggingEnabled(BuildConfig.DEBUG)','setWebContentsDebuggingEnabled(true)')},
 {id:'屏幕包含块与非活动层隔离',key:'css',test:s=>{assert.match(s.css,/will-change:transform/);assert.match(s.css,/\.screen\[aria-hidden=true\]\{pointer-events:none\}/);},bad:s=>s.replaceAll('will-change:transform','will-change:auto')},
 {id:'返回去重和进度同步',key:'nav',test:s=>{assert.match(s.nav,/now-lastBack.current<350/);assert.match(s.nav,/phase==='progress'\)document.documentElement.style.setProperty/);assert.doesNotMatch(s.nav,/requestAnimationFrame\(/);},bad:s=>s.replace('now-lastBack.current<350','now-lastBack.current<0')},
 {id:'手势期间禁用玻璃重算',key:'css',test:s=>assert.match(s.css,/\.gesturing \.dock,[^}]+backdrop-filter:none/),bad:s=>s.replace('backdrop-filter:none;filter:none;background:var(--surface)','backdrop-filter:blur(30px);filter:none;background:var(--surface)')},
 {id:'教材按钮完整胶囊与换行',key:'css',test:s=>{assert.match(s.css,/\.book-actions\{display:flex;flex-wrap:wrap/);assert.match(s.css,/\.book-actions>\*\{[^}]*border-radius:24px/);},bad:s=>s.replace('.book-actions{display:flex;flex-wrap:wrap','.book-actions{display:flex;flex-wrap:nowrap')},
 {id:'弹层起点缩放下限',key:'sheet',test:s=>{assert.match(s.sheet,/Math.max\(\.6,/);assert.match(s.sheet,/Math.max\(\.35,/);},bad:s=>s.replace('Math.max(.35,','Math.max(.02,')},
 {id:'设置首页分组顺序',key:'settings',test:s=>assert.deepEqual([...s.settings.split('export const ROUTE_TITLES')[0].matchAll(/title:'([^']+)'/g)].map(m=>m[1]),['主页','课表编辑','外观','实时通知','导航与学校','关于']),bad:s=>s.replace("title:'外观'","title:'错误分组'")},
 {id:'空导入明确失败',key:'import',test:s=>assert.match(s.import,/if\(!input.length\) fail\('没有可导入的课程/),bad:s=>s.replace('if(!input.length)','if(false)')},
 {id:'学年周次推断与设备总量保护',key:'import',test:s=>{assert.match(s.import,/parseNumbers\(v,999,'周次'\)/);assert.match(s.import,/instances>20_000/);assert.match(s.import,/weeks=detected\|\|52/);},bad:s=>s.replace("parseNumbers(v,999,'周次')","parseNumbers(v,53,'周次')")},
 {id:'折射只在选中胶囊并可自动降级',key:'css',test:s=>{assert.match(s.css,/\.dock\[data-droplet-ready=true\] \.dock-droplet-window\{backdrop-filter:url\(#glass-droplet\)/);assert.match(s.css,/\[data-performance=reduced\][^}]+\.dock-droplet-window\{backdrop-filter:blur\(1px\)/);assert.doesNotMatch(s.css,/dock-scrolling|glass-refraction/);},bad:s=>s.replace('backdrop-filter:url(#glass-droplet)','backdrop-filter:none')},
 {id:'Android 权限限定为日历、实时通知和更新联网',key:'manifest',test:s=>{const granted=[...s.manifest.matchAll(/<uses-permission(?:-sdk-?\d+)?\b[^>]*android:name="([^"]+)"/g)].map(m=>m[1]).sort();assert.deepEqual(granted,['android.permission.INTERNET','android.permission.POST_NOTIFICATIONS','android.permission.POST_PROMOTED_NOTIFICATIONS','android.permission.READ_CALENDAR','android.permission.WRITE_CALENDAR']);assert.doesNotMatch(s.manifest,/BOOT_COMPLETED|LOCKED_BOOT_COMPLETED|SCHEDULE_EXACT_ALARM/);},bad:s=>s.replace('</manifest>','<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" /></manifest>')},
 {id:'运行时授权仅在日历和通知范围',key:'native',test:s=>{const calls=[...s.native.matchAll(/\brequestPermissions\s*\(\s*arrayOf\s*\(([^)]*)\)/g)];assert.equal(calls.length,[...s.native.matchAll(/\brequestPermissions\s*\(/g)].length,'授权必须使用可审计的直接权限列表');for(const call of calls){assert.match(call[1],/^\s*Manifest\.permission\.[A-Z_]+(?:\s*,\s*Manifest\.permission\.[A-Z_]+)*\s*$/);for(const permission of call[1].matchAll(/Manifest\.permission\.([A-Z_]+)/g))assert.ok(['POST_NOTIFICATIONS','READ_CALENDAR','WRITE_CALENDAR'].includes(permission[1]),'超出已授权权限范围：'+permission[1]);}},bad:s=>s.replace('arrayOf(Manifest.permission.POST_NOTIFICATIONS)','arrayOf(Manifest.permission.READ_CONTACTS)')},
 {id:'无需额外授权的提醒调度和恢复',key:'scheduler',test:s=>{assert.match(s.scheduler,/setAndAllowWhileIdle/);assert.match(s.scheduler,/nextReminder/);assert.match(s.native,/onResume\(\)[^\n]*ReminderScheduler.enqueue/);assert.match(s.scheduler,/ACTION_MY_PACKAGE_REPLACED/);assert.match(s.scheduler,/ACTION_TIME_CHANGED/);assert.match(s.scheduler,/ACTION_TIMEZONE_CHANGED/);assert.doesNotMatch(s.scheduler+s.notifications,/setExact|canScheduleExactAlarms|ACTION_BOOT_COMPLETED|ACTION_SCHEDULE_EXACT_ALARM/);},bad:s=>s.replace('alarm.setAndAllowWhileIdle','alarm.setExactAndAllowWhileIdle')},
 {id:'无自启动电池豁免及后台弹出设置入口',key:'native',test:s=>{assert.doesNotMatch(s.native+s.settings+s.scheduler+s.notifications,/exactAlarmSettings|ACTION_REQUEST_SCHEDULE_EXACT_ALARM|ACTION_MANAGE_OVERLAY_PERMISSION|ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS|ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS|setFullScreenIntent|Autostart|AutoStart|autostart|BACKGROUND_ACTIVITY_START_ALLOWED|后台弹出|自启动/);},bad:s=>s+'\n// Settings.ACTION_MANAGE_OVERLAY_PERMISSION'},
 {id:'剪贴板仅保留用户主动复制',key:'webNative',test:s=>{assert.match(s.webNative,/navigator.clipboard\.writeText\(text\)/);assert.doesNotMatch(s.webNative+s.native,/clipboard\??\.(?:read|readText)|clipboard-read|getPrimaryClip|READ_CLIPBOARD|READ_CLIPBOARD_IN_BACKGROUND/);},bad:s=>s+'\n navigator.clipboard.readText();'},
 {id:'实时通知不强制着色',key:'notifications',test:s=>{assert.doesNotMatch(s.notifications,/setColorized\(true\)/);assert.match(s.notifications,/android.requestPromotedOngoing/);assert.match(s.manifest,/POST_PROMOTED_NOTIFICATIONS/);},bad:s=>s+'\n// setColorized(true)'}
];
for(const rule of rules){rule.test(sources);const broken={...sources,[rule.key]:rule.bad(sources[rule.key])};assert.notEqual(broken[rule.key],sources[rule.key],rule.id+'变异未生效');assert.throws(()=>rule.test(broken),undefined,rule.id+'守卫不能拦截变异');rule.test(sources);console.log(`PASS ${rule.id}（原始通过 → 变异拒绝 → 恢复通过）`);}
async function walk(dir){let output=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())output.push(...await walk(p));else if(/\.(?:ts|tsx|css|kt|xml)$/.test(p))output.push(p);}return output;}
for(const file of await walk('web/src')){const src=await readFile(file,'utf8');assert.doesNotMatch(src,/(?:src|href)=["']\/(?!\/)/,file+'根路径资源');assert.doesNotMatch(src,new RegExp(['Tesse'+'ract','Open'+'CV','local'+'Storage\\.setItem'].join('|'),'i'),file+'关停功能或错误存储');}
await mkdir('build/evidence',{recursive:true});await writeFile('build/evidence/source-guards.json',JSON.stringify({version,rules:rules.map(r=>({name:r.id,valid:true,mutationRejected:true,restored:true}))},null,2));
console.log(`${rules.length} 条工程守卫及双向变异验证通过。`);
